-- 1. Custom Types
create type public.user_role as enum ('admin', 'cashier', 'owner');
create type public.payment_method as enum ('cash', 'debit_card', 'credit_card', 'e_wallet', 'bank_transfer');

-- 2. Users Table
-- This table stores public user data and is linked to Supabase's auth.users table.
create table public.users (
  id uuid not null references auth.users on delete cascade,
  full_name text,
  role user_role not null default 'cashier',
  primary key (id)
);

-- Function to automatically create a public user profile when a new auth user signs up.
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.users (id, full_name, role)
  values (new.id, new.raw_user_meta_data->>'full_name', 'cashier');
  return new;
end;
$$;

-- Trigger to execute the function upon new user creation.
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 3. Categories Table
create table public.categories (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  color text
);
alter table public.categories enable row level security;

-- 4. Products Table
create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  sku text unique,
  barcode text unique,
  category_id bigint references public.categories on delete set null,
  cost_price numeric(10, 2),
  selling_price numeric(10, 2) not null,
  current_stock integer not null default 0,
  unit text, -- e.g., 'kg', 'pcs', 'pack'
  image_url text,
  low_stock_threshold integer not null default 10
);
alter table public.products enable row level security;

-- 5. Transactions Table
create table public.transactions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  total_amount numeric(10, 2) not null,
  discount_percent numeric(5, 2) default 0,
  discount_amount numeric(10, 2) default 0,
  tax_rate numeric(5, 2) default 0,
  tax_amount numeric(10, 2) default 0,
  grand_total numeric(10, 2) not null,
  payment_method payment_method not null,
  notes text,
  customer_name text,
  cashier_id uuid not null references auth.users on delete set null
);
alter table public.transactions enable row level security;

-- 6. Transaction Items Table
create table public.transaction_items (
  id bigint generated by default as identity primary key,
  transaction_id bigint not null references public.transactions on delete cascade,
  product_id bigint not null references public.products on delete restrict,
  quantity integer not null,
  unit_price numeric(10, 2) not null,
  subtotal numeric(10, 2) not null
);
alter table public.transaction_items enable row level security;

-- 7. RLS Policies
-- Helper function to get user role
create or replace function public.get_user_role(user_id uuid)
returns text
language plpgsql
security definer set search_path = public
as $$
declare
  user_role_text text;
begin
  select role::text into user_role_text from public.users where id = user_id;
  return user_role_text;
end;
$$;

-- Users Table RLS
create policy "Allow users to see their own profile" on public.users
  for select using (auth.uid() = id);
create policy "Allow admin/owner to see all profiles" on public.users
  for select using (public.get_user_role(auth.uid()) in ('admin', 'owner'));
create policy "Allow admin/owner to update profiles" on public.users
  for update using (public.get_user_role(auth.uid()) in ('admin', 'owner'));

-- Categories Table RLS
create policy "Allow authenticated users to read categories" on public.categories
  for select using (auth.role() = 'authenticated');
create policy "Allow admin/owner to manage categories" on public.categories
  for all using (public.get_user_role(auth.uid()) in ('admin', 'owner'));

-- Products Table RLS
create policy "Allow authenticated users to read products" on public.products
  for select using (auth.role() = 'authenticated');
create policy "Allow admin/owner to manage products" on public.products
  for all using (public.get_user_role(auth.uid()) in ('admin', 'owner'));

-- Transactions Table RLS
create policy "Allow admin/owner to see all transactions" on public.transactions
  for select using (public.get_user_role(auth.uid()) in ('admin', 'owner'));
create policy "Allow cashiers to see their own transactions" on public.transactions
  for select using (cashier_id = auth.uid());
create policy "Allow authenticated users to create transactions" on public.transactions
  for insert with check (auth.role() = 'authenticated');

-- Transaction Items Table RLS
create policy "Allow users to see items of transactions they can access" on public.transaction_items
  for select using (
    exists (
      select 1 from public.transactions
      where id = transaction_id
    )
  );
create policy "Allow authenticated users to create transaction items" on public.transaction_items
  for insert with check (auth.role() = 'authenticated');

-- 8. Function to update stock
create or replace function public.update_product_stock()
returns trigger
language plpgsql
as $$
begin
  update public.products
  set current_stock = current_stock - new.quantity
  where id = new.product_id;
  return new;
end;
$$;

-- Trigger to update stock after a transaction item is inserted
create trigger on_transaction_item_insert
  after insert on public.transaction_items
  for each row execute procedure public.update_product_stock();

-- 9. Seed Data
-- Seed Categories
insert into public.categories (name, color) values
('Drinks', '#3b82f6'),
('Snacks', '#f97316'),
('Noodles', '#ef4444'),
('Groceries', '#22c55e'),
('Toiletries', '#8b5cf6');

-- Seed Products
insert into public.products (name, sku, barcode, category_id, cost_price, selling_price, current_stock, unit, low_stock_threshold) values
('Milo 3-in-1 (18 sticks)', 'MLO-3IN1-18', '9556001214356', 1, 12.50, 15.90, 50, 'pack', 10),
('Maggi Mee Goreng (5 pack)', 'MGI-GORENG-5', '8888240101024', 3, 4.50, 5.80, 100, 'pack', 20),
('100 Plus Isotonic Drink 1.5L', '100P-1.5L', '9556322980017', 1, 3.00, 4.20, 80, 'bottle', 15),
('Gardenia Original Classic Bread', 'GDN-BRD-CLS', '9556072000013', 4, 2.80, 3.50, 30, 'loaf', 10),
('Mister Potato Crisps Original 150g', 'MTP-CRSP-ORG', '9556272800012', 2, 3.50, 4.80, 60, 'can', 10),
('Saji Cooking Oil 1kg', 'SJI-OIL-1KG', '9556166000011', 4, 6.50, 8.00, 40, 'bottle', 10),
('Dutch Lady UHT Full Cream Milk 1L', 'DL-MILK-1L', '8712400000015', 1, 5.00, 6.50, 70, 'carton', 15),
('Colgate Total Toothpaste 150g', 'CLG-TP-150G', '8850006920019', 5, 8.00, 10.50, 50, 'tube', 10);